### ISSUE TITLE
Pre-patch 9.0.1 Cache

### ISSUE THREAD

**Issue by JanGalek** [Bromeego/WoW-Cache#1]
Hi, should you add cache for pre-patch 9.0.1 ? Thank you

**Comment by Bromeego** [comment]
Hi,
I will pull out my PC and set it back up and upload the cache for 9.0.1.
Apologies but as real life has taken over my PC gaming has been pushed aside :(.
I will try and get this up as soon as possible.
Thanks

**Comment by Bromeego** [comment]
Ran around a bunch within Stormwind and Ironforge. Opened all the windows.
I don't have a subscription but I hope this will do. Was doing it on my old bank alt.
Let me know if there are any issues
